name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    
    steps:
    - run: git checkout master  
    - run: git pull origin master  
    - run: npm run test
