name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checkout: 
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3
    with:
      ref: master
  test:
    runs-on: ubuntu-latest
    name: Testing
    
    steps:
    - run: git checkout master  
    - run: git pull master  
    - run: npm run test
