name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
  test:
    runs-on: ubuntu-latest
    name: Testing
    needs: checkout
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run test
