name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Nx Cloud - Main Job
    
    steps:
    - uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    - name: Cache node modules
    - run: npm run test

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3
