name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
  test:
    runs-on: ubuntu-latest
    name: Testing
    needs: checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - name: Use Node.js for Test
      uses: actions/setup-node@v3
      with:
        node-version: 16
    # - run: npm run test
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
          browser: chrome
